### ISSUE TITLE
ModuleNotFoundError: No module named 'face_alignment'

### ISSUE THREAD

**Issue by Wangzhipeng777** [hahahappyboy/GANForCartoon#1]
File "main.py", line 13, in <module>
    from utils.face_detect import FaceDetect
  File "/home/deeplab/python370/GANForCartoon-main/utils/face_detect.py", line 4, in <module>
    import face_alignment
ModuleNotFoundError: No module named 'face_alignment'

**Comment by hahahappyboy** [comment]
pip install face_alignment

**Comment by Wangzhipeng777** [comment]
Sorry, I thought it was a missing file

**Comment by hahahappyboy** [comment]
Pleasure to answer your question
